stages:
  - install
  - test
  - build
  - deploy

image: node:latest

install:
  stage: install
  script:
    - npm install
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules

test:
  stage: test
  script:
    - npm run test:e2e
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

lint:
  stage: test
  script:
    - npm run lint
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

audit:
  stage: test
  script:
    - npm audit
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

deploy:
  stage: deploy
  script:
    - echo "Pushing to docker registry"
  when: manual
  only:
    - main