stages:
  - install
  - build
  - test
  - deploy

install:
  image: node:16-alpine
  stage: install
  script:
    - npm install

build:
  image: node:16-alpine
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - "dist/"

lint:
image: node:16-alpine
 stage: test
 script:
   - npm run lint
 allow_failure: true

audit:
  image: node:16-alpine
  stage: test
  script:
    - npm audit
  allow_failure: true

deploy:
  image: node:16-alpine
  stage: deploy
  environment: production
  script:
    - echo "Deploying the app"
