stages:
  - checking
  - build
  - deploy

image: node:latest

checking:
  stage: checking
  script:
    - echo "Running tests"

lint:
  stage: checking
  script:
    - echo "Running eslint files check"

audit:
  stage: checking
  script:
    - echo "Running npm audit"

build:
  stage: build
  script:
    - echo "Building docker image"

deploy:
  stage: deploy
  script:
    - echo "Pushing to docker registry"
  when: manual
  only:
    - main